// Generated by merge.py
// Do not edit by hand; edit src/ instead.
#![allow(dead_code, unused_imports)]

// --- src/types.rs ---
pub mod types {
    // types.rs — from types.hpp

    pub const ROWS: usize = 10;
    pub const COLS: usize = 17;

    pub const FIRST_PLAYER: i8 = 1;
    pub const SECOND_PLAYER: i8 = -1;
    pub const NO_OWNER: i8 = 0;

    pub type ValueGrid = [[i8; COLS]; ROWS];
    pub type OwnerGrid = [[i8; COLS]; ROWS];

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum ShapeClass {
        Rect1x2 = 0,
        Rect2x1 = 1,
        Rect1x3 = 2,
        Rect3x1 = 3,
        Rect2x2 = 4,
        Rect1x4 = 5,
        Rect4x1 = 6,
        RectOther = 7,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum Orientation {
        Square = 0,
        Portrait = 1,
        Landscape = 2,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum RegionTag {
        Corner = 0,
        Edge = 1,
        CenterOuter = 2,
        CenterInner = 3,
        None = 4,
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    #[repr(u32)]
    pub enum KnownStyle {
        Unknown = 0,
        CordycepsAttack = 1,
        CordycepsDefense = 2,
        CordycepsBalanced = 3,
        RustOld = 4,
        RustUpdate = 5,
    }

    #[derive(Clone, Debug, Default)]
    pub struct MovePriorConfig {
        pub shape_boost: [i16; 8],
        pub medium_rect_boost: i16,
        pub barrier_boost: i16,
        pub connection_boost: i16,
        pub dead_cell_risk_penalty: i16,
        pub side_boost_first: i16,
        pub side_boost_second: i16,
        pub max_total_adjustment: u16,
        pub confidence_min: u8,
    }

    impl MovePriorConfig {
        pub fn new_default() -> Self {
            MovePriorConfig {
                shape_boost: [0; 8],
                medium_rect_boost: 0,
                barrier_boost: 0,
                connection_boost: 0,
                dead_cell_risk_penalty: 0,
                side_boost_first: 0,
                side_boost_second: 0,
                max_total_adjustment: 3000,
                confidence_min: 60,
            }
        }
    }

    #[derive(Clone, Copy, Debug, Default)]
    #[repr(align(16))]
    pub struct FeatureVector8 {
        pub dim: [i16; 8],
    }

    #[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
    pub struct Move {
        pub r1: i32,
        pub c1: i32,
        pub r2: i32,
        pub c2: i32,
        pub priority: i32,
    }

    impl Move {
        pub const fn pass() -> Self {
            Move { r1: -1, c1: -1, r2: -1, c2: -1, priority: 0 }
        }

        pub fn is_pass(&self) -> bool {
            self.r1 == -1 && self.c1 == -1 && self.r2 == -1 && self.c2 == -1
        }

        pub fn coords_eq(&self, other: &Move) -> bool {
            self.r1 == other.r1 && self.c1 == other.c1
                && self.r2 == other.r2 && self.c2 == other.c2
        }
    }

    pub const PASS_MOVE: Move = Move::pass();

    #[inline]
    pub const fn opponent(player: i8) -> i8 {
        -player
    }

    #[inline]
    pub fn classify_shape(r1: i32, c1: i32, r2: i32, c2: i32) -> ShapeClass {
        let h = r2 - r1 + 1;
        let w = c2 - c1 + 1;
        match (h, w) {
            (1, 2) => ShapeClass::Rect1x2,
            (2, 1) => ShapeClass::Rect2x1,
            (1, 3) => ShapeClass::Rect1x3,
            (3, 1) => ShapeClass::Rect3x1,
            (2, 2) => ShapeClass::Rect2x2,
            (1, 4) => ShapeClass::Rect1x4,
            (4, 1) => ShapeClass::Rect4x1,
            _ => ShapeClass::RectOther,
        }
    }

    #[inline]
    pub fn classify_orientation(r1: i32, c1: i32, r2: i32, c2: i32) -> Orientation {
        let h = r2 - r1 + 1;
        let w = c2 - c1 + 1;
        if h == w {
            Orientation::Square
        } else if h > w {
            Orientation::Portrait
        } else {
            Orientation::Landscape
        }
    }

    #[inline]
    pub fn classify_region(r1: i32, c1: i32, r2: i32, c2: i32) -> RegionTag {
        let near_corner = (r1 <= 1 && c1 <= 1)
            || (r1 <= 1 && c2 >= COLS as i32 - 2)
            || (r2 >= ROWS as i32 - 2 && c1 <= 1)
            || (r2 >= ROWS as i32 - 2 && c2 >= COLS as i32 - 2);
        if near_corner {
            return RegionTag::Corner;
        }
        let near_edge = r1 == 0 || r2 == ROWS as i32 - 1 || c1 == 0 || c2 == COLS as i32 - 1;
        if near_edge {
            return RegionTag::Edge;
        }
        let cr = (r1 + r2) / 2;
        let cc = (c1 + c2) / 2;
        if cr >= 3 && cr <= 6 && cc >= 5 && cc <= 11 {
            RegionTag::CenterInner
        } else {
            RegionTag::CenterOuter
        }
    }

    #[inline]
    pub fn move_area(r1: i32, c1: i32, r2: i32, c2: i32) -> i32 {
        (r2 - r1 + 1) * (c2 - c1 + 1)
    }
}

// --- src/timer.rs ---
pub mod timer {
    // timer.rs — from timer.hpp

    use std::time::Instant;

    pub struct Timer {
        start: Instant,
    }

    impl Timer {
        pub fn new() -> Self {
            Timer { start: Instant::now() }
        }

        pub fn start(&mut self) {
            self.start = Instant::now();
        }

        pub fn elapsed_ms(&self) -> i64 {
            self.start.elapsed().as_millis() as i64
        }

        pub fn timed_out(&self, budget_ms: i64) -> bool {
            self.elapsed_ms() >= budget_ms
        }
    }
}

// --- src/board.rs ---
pub mod board {
    // board.rs — from board.hpp + board.cpp

    use crate::movegen::generate_legal_moves;
    use crate::opponent_db::G_ACTIVE_PRIOR_CONFIG;
    use crate::search::zobrist::{cell_hash, hash_board, passes_hash, player_hash};
    use crate::types::*;

    #[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
    pub struct EvalCache {
        pub owned_first: i32,
        pub owned_second: i32,
        pub connectivity_first: i32,
        pub connectivity_second: i32,
        pub corners_first: i32,
        pub corners_second: i32,
        pub edges_first: i32,
        pub edges_second: i32,
        pub live_adjacent_first: i32,
        pub live_adjacent_second: i32,
    }

    // MoveRecord for undo — stores all changes made by a move.
    #[derive(Clone, Copy, Debug, Default)]
    pub struct CellChange {
        pub r: i8,
        pub c: i8,
        pub old_value: i8,
        pub old_owner: i8,
    }

    const MAX_CELL_CHANGES: usize = ROWS * COLS;

    pub struct MoveRecord {
        pub changes: [CellChange; MAX_CELL_CHANGES],
        pub change_count: usize,
        pub old_player: i8,
        pub old_consecutive_passes: i32,
        pub old_hash: u64,
        pub old_eval_cache: EvalCache,
        pub was_pass: bool,
    }

    impl MoveRecord {
        pub fn new() -> Self {
            MoveRecord {
                changes: [CellChange::default(); MAX_CELL_CHANGES],
                change_count: 0,
                old_player: 0,
                old_consecutive_passes: 0,
                old_hash: 0,
                old_eval_cache: EvalCache::default(),
                was_pass: false,
            }
        }
    }

    #[derive(Clone)]
    pub struct Board {
        pub values: ValueGrid,
        pub owners: OwnerGrid,
        pub player: i8,
        pub consecutive_passes: i32,
        pub hash: u64,
        pub eval_cache: EvalCache,
    }

    impl Board {
        pub fn new() -> Self {
            let mut board = Board {
                values: [[0i8; COLS]; ROWS],
                owners: [[NO_OWNER; COLS]; ROWS],
                player: FIRST_PLAYER,
                consecutive_passes: 0,
                hash: 0,
                eval_cache: EvalCache::default(),
            };
            board.recompute_hash();
            board.recompute_eval_cache();
            board
        }

        fn recompute_hash(&mut self) {
            self.hash = hash_board(self);
        }

        fn recompute_eval_cache(&mut self) {
            self.eval_cache = EvalCache::default();
            for r in 0..ROWS {
                for c in 0..COLS {
                    let owner = self.owners[r][c];
                    Self::adjust_owner_count(&mut self.eval_cache, owner, 1);
                    if Self::cell_is_corner(r, c) {
                        Self::adjust_corner_count(&mut self.eval_cache, owner, 1);
                    }
                    if Self::cell_is_edge(r, c) {
                        Self::adjust_edge_count(&mut self.eval_cache, owner, 1);
                    }
                    if owner != NO_OWNER && self.cell_has_live_neighbor(r, c) {
                        Self::adjust_live_adjacent_count(&mut self.eval_cache, owner, 1);
                    }
                    if c + 1 < COLS && owner != NO_OWNER && self.owners[r][c + 1] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, 1);
                    }
                    if r + 1 < ROWS && owner != NO_OWNER && self.owners[r + 1][c] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, 1);
                    }
                }
            }
        }

        fn update_hash_before_turn_change(&mut self) {
            self.hash ^= player_hash(self.player);
            self.hash ^= passes_hash(self.consecutive_passes);
        }

        fn update_hash_after_turn_change(&mut self) {
            self.hash ^= player_hash(self.player);
            self.hash ^= passes_hash(self.consecutive_passes);
        }

        fn replace_cell(&mut self, r: usize, c: usize, new_value: i8, new_owner: i8) {
            self.hash ^= cell_hash(r, c, self.values[r][c], self.owners[r][c]);
            self.values[r][c] = new_value;
            self.owners[r][c] = new_owner;
            self.hash ^= cell_hash(r, c, self.values[r][c], self.owners[r][c]);
        }

        fn cell_has_live_neighbor(&self, r: usize, c: usize) -> bool {
            (r > 0 && self.values[r - 1][c] > 0)
                || (r + 1 < ROWS && self.values[r + 1][c] > 0)
                || (c > 0 && self.values[r][c - 1] > 0)
                || (c + 1 < COLS && self.values[r][c + 1] > 0)
        }

        fn cell_is_corner(r: usize, c: usize) -> bool {
            (r == 0 || r == ROWS - 1) && (c == 0 || c == COLS - 1)
        }

        fn cell_is_edge(r: usize, c: usize) -> bool {
            r == 0 || r == ROWS - 1 || c == 0 || c == COLS - 1
        }

        fn adjust_owner_count(cache: &mut EvalCache, owner: i8, delta: i32) {
            if owner == FIRST_PLAYER {
                cache.owned_first += delta;
            } else if owner == SECOND_PLAYER {
                cache.owned_second += delta;
            }
        }

        fn adjust_corner_count(cache: &mut EvalCache, owner: i8, delta: i32) {
            if owner == FIRST_PLAYER {
                cache.corners_first += delta;
            } else if owner == SECOND_PLAYER {
                cache.corners_second += delta;
            }
        }

        fn adjust_edge_count(cache: &mut EvalCache, owner: i8, delta: i32) {
            if owner == FIRST_PLAYER {
                cache.edges_first += delta;
            } else if owner == SECOND_PLAYER {
                cache.edges_second += delta;
            }
        }

        fn adjust_connectivity_count(cache: &mut EvalCache, owner: i8, delta: i32) {
            if owner == FIRST_PLAYER {
                cache.connectivity_first += delta;
            } else if owner == SECOND_PLAYER {
                cache.connectivity_second += delta;
            }
        }

        fn adjust_live_adjacent_count(cache: &mut EvalCache, owner: i8, delta: i32) {
            if owner == FIRST_PLAYER {
                cache.live_adjacent_first += delta;
            } else if owner == SECOND_PLAYER {
                cache.live_adjacent_second += delta;
            }
        }

        fn add_flag(flagged: &mut [[bool; COLS]; ROWS], r: i32, c: i32) {
            if r >= 0 && r < ROWS as i32 && c >= 0 && c < COLS as i32 {
                flagged[r as usize][c as usize] = true;
            }
        }

        fn update_eval_cache_for_move(&mut self, mv: &Move) {
            if mv.is_pass() {
                return;
            }

            let mut impacted = [[false; COLS]; ROWS];
            let mut changed = [[false; COLS]; ROWS];
            for r in mv.r1..=mv.r2 {
                for c in mv.c1..=mv.c2 {
                    let ru = r as usize;
                    let cu = c as usize;
                    changed[ru][cu] = true;
                    Self::add_flag(&mut impacted, r, c);
                    Self::add_flag(&mut impacted, r - 1, c);
                    Self::add_flag(&mut impacted, r + 1, c);
                    Self::add_flag(&mut impacted, r, c - 1);
                    Self::add_flag(&mut impacted, r, c + 1);
                }
            }

            for r in 0..ROWS {
                for c in 0..COLS {
                    if !impacted[r][c] {
                        continue;
                    }
                    let owner = self.owners[r][c];
                    if owner != NO_OWNER && self.cell_has_live_neighbor(r, c) {
                        Self::adjust_live_adjacent_count(&mut self.eval_cache, owner, -1);
                    }
                }
            }

            for r in 0..ROWS {
                for c in 0..COLS {
                    let owner = self.owners[r][c];
                    if owner == NO_OWNER {
                        continue;
                    }
                    if c + 1 < COLS && (changed[r][c] || changed[r][c + 1]) && self.owners[r][c + 1] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, -1);
                    }
                    if r + 1 < ROWS && (changed[r][c] || changed[r + 1][c]) && self.owners[r + 1][c] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, -1);
                    }
                }
            }

            for r in mv.r1..=mv.r2 {
                for c in mv.c1..=mv.c2 {
                    let ru = r as usize;
                    let cu = c as usize;
                    let old_owner = self.owners[ru][cu];
                    Self::adjust_owner_count(&mut self.eval_cache, old_owner, -1);
                    if Self::cell_is_corner(ru, cu) {
                        Self::adjust_corner_count(&mut self.eval_cache, old_owner, -1);
                    }
                    if Self::cell_is_edge(ru, cu) {
                        Self::adjust_edge_count(&mut self.eval_cache, old_owner, -1);
                    }

                    self.replace_cell(ru, cu, 0, self.player);

                    let new_owner = self.owners[ru][cu];
                    Self::adjust_owner_count(&mut self.eval_cache, new_owner, 1);
                    if Self::cell_is_corner(ru, cu) {
                        Self::adjust_corner_count(&mut self.eval_cache, new_owner, 1);
                    }
                    if Self::cell_is_edge(ru, cu) {
                        Self::adjust_edge_count(&mut self.eval_cache, new_owner, 1);
                    }
                }
            }

            for r in 0..ROWS {
                for c in 0..COLS {
                    let owner = self.owners[r][c];
                    if owner == NO_OWNER {
                        continue;
                    }
                    if c + 1 < COLS && (changed[r][c] || changed[r][c + 1]) && self.owners[r][c + 1] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, 1);
                    }
                    if r + 1 < ROWS && (changed[r][c] || changed[r + 1][c]) && self.owners[r + 1][c] == owner {
                        Self::adjust_connectivity_count(&mut self.eval_cache, owner, 1);
                    }
                }
            }

            for r in 0..ROWS {
                for c in 0..COLS {
                    if !impacted[r][c] {
                        continue;
                    }
                    let owner = self.owners[r][c];
                    if owner != NO_OWNER && self.cell_has_live_neighbor(r, c) {
                        Self::adjust_live_adjacent_count(&mut self.eval_cache, owner, 1);
                    }
                }
            }
        }

        pub fn init_from_string(&mut self, board_str: &str) {
            let mut tokens = board_str.split_whitespace();
            for r in 0..ROWS {
                let row_str = tokens.next().expect("INIT: insufficient rows (expected 10)");
                assert_eq!(
                    row_str.len(),
                    COLS,
                    "INIT: row {} has {} columns, expected {}",
                    r,
                    row_str.len(),
                    COLS
                );
                for (c, ch) in row_str.chars().enumerate() {
                    assert!(ch.is_ascii_digit(), "INIT: invalid digit '{}' at ({},{})", ch, r, c);
                    self.values[r][c] = (ch as u8 - b'0') as i8;
                }
            }
            for row in self.owners.iter_mut() {
                row.fill(NO_OWNER);
            }
            self.consecutive_passes = 0;
            self.recompute_hash();
            self.recompute_eval_cache();
        }

        pub fn apply_pass(&mut self) {
            self.update_hash_before_turn_change();
            self.consecutive_passes += 1;
            self.player = opponent(self.player);
            self.update_hash_after_turn_change();
        }

        pub fn apply_move(&mut self, mv: &Move) {
            if mv.is_pass() {
                self.apply_pass();
                return;
            }
            self.update_hash_before_turn_change();
            self.update_eval_cache_for_move(mv);
            self.consecutive_passes = 0;
            self.player = opponent(self.player);
            self.update_hash_after_turn_change();
        }

        pub fn make_move(&mut self, mv: &Move, record: &mut MoveRecord) {
            record.old_player = self.player;
            record.old_consecutive_passes = self.consecutive_passes;
            record.old_hash = self.hash;
            record.old_eval_cache = self.eval_cache;
            record.change_count = 0;

            if mv.is_pass() {
                record.was_pass = true;
                self.update_hash_before_turn_change();
                self.consecutive_passes += 1;
                self.player = opponent(self.player);
                self.update_hash_after_turn_change();
                return;
            }

            record.was_pass = false;
            self.update_hash_before_turn_change();
            for r in mv.r1..=mv.r2 {
                for c in mv.c1..=mv.c2 {
                    record.changes[record.change_count] = CellChange {
                        r: r as i8,
                        c: c as i8,
                        old_value: self.values[r as usize][c as usize],
                        old_owner: self.owners[r as usize][c as usize],
                    };
                    record.change_count += 1;
                }
            }
            self.update_eval_cache_for_move(mv);
            self.consecutive_passes = 0;
            self.player = opponent(self.player);
            self.update_hash_after_turn_change();
        }

        pub fn unmake_move(&mut self, record: &MoveRecord) {
            self.player = record.old_player;
            self.consecutive_passes = record.old_consecutive_passes;
            self.hash = record.old_hash;
            self.eval_cache = record.old_eval_cache;
            if record.was_pass {
                return;
            }
            for ch in &record.changes[..record.change_count] {
                self.values[ch.r as usize][ch.c as usize] = ch.old_value;
                self.owners[ch.r as usize][ch.c as usize] = ch.old_owner;
            }
        }

        pub fn is_legal_move(&self, mv: &Move) -> bool {
            if mv.is_pass() {
                return true;
            }
            if mv.r1 < 0 || mv.r2 >= ROWS as i32 || mv.c1 < 0 || mv.c2 >= COLS as i32 {
                return false;
            }
            if mv.r1 > mv.r2 || mv.c1 > mv.c2 {
                return false;
            }
            let mut sum = 0i32;
            for r in mv.r1..=mv.r2 {
                for c in mv.c1..=mv.c2 {
                    let v = self.values[r as usize][c as usize];
                    if v > 0 {
                        sum += v as i32;
                        if sum > 10 {
                            return false;
                        }
                    }
                }
            }
            if sum != 10 {
                return false;
            }
            let mut top = false;
            let mut bottom = false;
            let mut left = false;
            let mut right = false;
            for c in mv.c1..=mv.c2 {
                if self.values[mv.r1 as usize][c as usize] > 0 {
                    top = true;
                }
                if self.values[mv.r2 as usize][c as usize] > 0 {
                    bottom = true;
                }
            }
            for r in mv.r1..=mv.r2 {
                if self.values[r as usize][mv.c1 as usize] > 0 {
                    left = true;
                }
                if self.values[r as usize][mv.c2 as usize] > 0 {
                    right = true;
                }
            }
            top && bottom && left && right
        }

        pub fn legal_moves(&self) -> Vec<Move> {
            let mut moves = generate_legal_moves(&self.values);
            let cfg_ptr = G_ACTIVE_PRIOR_CONFIG.load(std::sync::atomic::Ordering::Relaxed);
            for m in moves.iter_mut() {
                if m.is_pass() {
                    m.priority = 0;
                    continue;
                }
                let mut steal = 0i32;
                let area = (m.r2 - m.r1 + 1) * (m.c2 - m.c1 + 1);
                for r in m.r1..=m.r2 {
                    for c in m.c1..=m.c2 {
                        if self.owners[r as usize][c as usize] == opponent(self.player) {
                            steal += 1;
                        }
                    }
                }
                let height = m.r2 - m.r1 + 1;
                let width = m.c2 - m.c1 + 1;
                let portrait_bonus = if height > width { 500 } else { 0 };
                let small_bonus = if area <= 4 { 300 } else { 0 };
                m.priority = steal * 1000 + area + portrait_bonus + small_bonus;

                    if !cfg_ptr.is_null() {
                        let cfg = unsafe { &*cfg_ptr };
                        let mut adj = 0i32;
                        let sc = classify_shape(m.r1, m.c1, m.r2, m.c2) as usize;
                        adj += cfg.shape_boost[sc] as i32;
                        if self.player == FIRST_PLAYER {
                            adj += cfg.side_boost_first as i32;
                        } else if self.player == SECOND_PLAYER {
                            adj += cfg.side_boost_second as i32;
                        }
                        if area >= 5 && area <= 10 {
                            adj += cfg.medium_rect_boost as i32;
                        }
                    if self.barrier_potential(m.r1, m.c1, m.r2, m.c2) > 0 {
                        adj += cfg.barrier_boost as i32;
                    }
                    adj += self.connectivity_boost(m.r1, m.c1, m.r2, m.c2)
                        * cfg.connection_boost as i32
                        / 4;
                    adj -= self.dead_cell_risk_proxy(m.r1, m.c1, m.r2, m.c2)
                        * cfg.dead_cell_risk_penalty as i32
                        / 4;
                    let cap = cfg.max_total_adjustment as i32;
                    adj = adj.clamp(-cap, cap);
                    m.priority += adj;
                }
            }
            moves
        }

        pub fn owned_cells(&self, player: i8) -> i32 {
            if player == FIRST_PLAYER {
                self.eval_cache.owned_first
            } else if player == SECOND_PLAYER {
                self.eval_cache.owned_second
            } else {
                0
            }
        }

        pub fn barrier_potential(&self, r1: i32, c1: i32, r2: i32, c2: i32) -> i32 {
            let h = r2 - r1 + 1;
            let w = c2 - c1 + 1;
            if h >= 4 && w <= 2 {
                let cc = (c1 + c2) / 2;
                if cc >= 4 && cc <= 12 {
                    return 2;
                }
                return 1;
            }
            if w >= 6 && h <= 2 {
                let cr = (r1 + r2) / 2;
                if cr >= 3 && cr <= 6 {
                    return 2;
                }
                return 1;
            }
            0
        }

        pub fn dead_cell_risk_proxy(&self, r1: i32, c1: i32, r2: i32, c2: i32) -> i32 {
            let mut risk = 0i32;
            for r in r1..=r2 {
                for c in c1..=c2 {
                    let ru = r as usize;
                    let cu = c as usize;
                    if self.owners[ru][cu] == self.player {
                        continue;
                    }
                    let mut protection = 0i32;
                    if r > 0 && self.owners[ru - 1][cu] == self.player {
                        protection += 1;
                    }
                    if r < ROWS as i32 - 1 && self.owners[ru + 1][cu] == self.player {
                        protection += 1;
                    }
                    if c > 0 && self.owners[ru][cu - 1] == self.player {
                        protection += 1;
                    }
                    if c < COLS as i32 - 1 && self.owners[ru][cu + 1] == self.player {
                        protection += 1;
                    }
                    let adjacent_live = self.cell_has_live_neighbor(ru, cu);
                    if protection == 0 && adjacent_live {
                        risk += 2;
                    } else if protection <= 1 && adjacent_live {
                        risk += 1;
                    }
                }
            }
            risk
        }

        pub fn connectivity_boost(&self, r1: i32, c1: i32, r2: i32, c2: i32) -> i32 {
            let mut boost = 0i32;
            for r in r1..=r2 {
                for c in c1..=c2 {
                    let ru = r as usize;
                    let cu = c as usize;
                    if self.owners[ru][cu] == self.player {
                        continue;
                    }
                    if r > 0 && self.owners[ru - 1][cu] == self.player {
                        boost += 1;
                    }
                    if r < ROWS as i32 - 1 && self.owners[ru + 1][cu] == self.player {
                        boost += 1;
                    }
                    if c > 0 && self.owners[ru][cu - 1] == self.player {
                        boost += 1;
                    }
                    if c < COLS as i32 - 1 && self.owners[ru][cu + 1] == self.player {
                        boost += 1;
                    }
                }
            }
            boost
        }
    }
}

// --- src/movegen.rs ---
pub mod movegen {
    // movegen.rs — from movegen.hpp + movegen.cpp

    use crate::types::*;

    type PrefixSum = [[i32; COLS + 1]; ROWS + 1];

    fn build_prefix_sum(values: &ValueGrid) -> PrefixSum {
        let mut pref = [[0i32; COLS + 1]; ROWS + 1];
        for r in 0..ROWS {
            for c in 0..COLS {
                let val = if values[r][c] > 0 { values[r][c] as i32 } else { 0 };
                pref[r + 1][c + 1] = val + pref[r][c + 1] + pref[r + 1][c] - pref[r][c];
            }
        }
        pref
    }

    #[inline]
    fn rect_sum(pref: &PrefixSum, r1: usize, c1: usize, r2: usize, c2: usize) -> i32 {
        pref[r2 + 1][c2 + 1] - pref[r1][c2 + 1] - pref[r2 + 1][c1] + pref[r1][c1]
    }

    fn check_inscribed(values: &ValueGrid, r1: usize, c1: usize, r2: usize, c2: usize) -> bool {
        let mut top = false;
        let mut bottom = false;
        let mut left = false;
        let mut right = false;

        for c in c1..=c2 {
            if values[r1][c] > 0 {
                top = true;
            }
            if values[r2][c] > 0 {
                bottom = true;
            }
        }
        for r in r1..=r2 {
            if values[r][c1] > 0 {
                left = true;
            }
            if values[r][c2] > 0 {
                right = true;
            }
        }
        top && bottom && left && right
    }

    pub fn generate_legal_moves(values: &ValueGrid) -> Vec<Move> {
        let mut moves = Vec::new();
        let pref = build_prefix_sum(values);

        for r1 in 0..ROWS {
            for r2 in r1..ROWS {
                for c1 in 0..COLS {
                    for c2 in c1..COLS {
                        let sum = rect_sum(&pref, r1, c1, r2, c2);
                        if sum > 10 {
                            // Row-band early break: sum only increases as c2 expands
                            break;
                        }
                        if sum == 10 && check_inscribed(values, r1, c1, r2, c2) {
                            moves.push(Move {
                                r1: r1 as i32,
                                c1: c1 as i32,
                                r2: r2 as i32,
                                c2: c2 as i32,
                                priority: 0,
                            });
                        }
                    }
                }
            }
        }
        moves
    }
}

// --- src/eval.rs ---
pub mod eval {
    // eval.rs — from eval.hpp + eval.cpp

    use std::sync::atomic::{AtomicU64, Ordering};
    use crate::board::Board;
    use crate::types::*;

    pub static EVAL_CALLS: AtomicU64 = AtomicU64::new(0);

    // eval weights — loaded once from EVAL_WEIGHTS_FILE or defaults
    static WEIGHTS: std::sync::OnceLock<EvalWeightSet> = std::sync::OnceLock::new();

    #[derive(Clone, Copy)]
    struct EvalWeights {
        territory: i32,
        mobility: i32,
        connectivity: i32,
        corners: i32,
        edges: i32,
        recapture: i32,
        vulnerability: i32,
    }

    struct EvalWeightSet {
        first: EvalWeights,
        second: EvalWeights,
    }

    fn get_weights() -> &'static EvalWeightSet {
        WEIGHTS.get_or_init(|| {
            // Try to load from EVAL_WEIGHTS_FILE env
            if let Ok(fname) = std::env::var("EVAL_WEIGHTS_FILE") {
                if let Ok(content) = std::fs::read_to_string(&fname) {
                    let nums: Vec<i32> = content
                        .split_whitespace()
                        .filter_map(|s| s.parse().ok())
                        .collect();
                    if nums.len() >= 14 {
                        return EvalWeightSet {
                            first: EvalWeights {
                                territory: nums[0],
                                mobility: nums[1],
                                connectivity: nums[2],
                                corners: nums[3],
                                edges: nums[4],
                                recapture: nums[5],
                                vulnerability: nums[6],
                            },
                            second: EvalWeights {
                                territory: nums[7],
                                mobility: nums[8],
                                connectivity: nums[9],
                                corners: nums[10],
                                edges: nums[11],
                                recapture: nums[12],
                                vulnerability: nums[13],
                            },
                        };
                    }
                    if nums.len() >= 7 {
                        let shared = EvalWeights {
                            territory: nums[0],
                            mobility: nums[1],
                            connectivity: nums[2],
                            corners: nums[3],
                            edges: nums[4],
                            recapture: nums[5],
                            vulnerability: nums[6],
                        };
                        return EvalWeightSet {
                            first: shared,
                            second: shared,
                        };
                    }
                }
            }
            EvalWeightSet {
                first: EvalWeights {
                    territory: 148,
                    mobility: 20,
                    connectivity: 19,
                    corners: 18,
                    edges: 3,
                    recapture: 39,
                    vulnerability: 9,
                },
                second: EvalWeights {
                    territory: 140,
                    mobility: 16,
                    connectivity: 28,
                    corners: 20,
                    edges: 6,
                    recapture: 28,
                    vulnerability: 18,
                },
            }
        })
    }

    pub fn evaluate(board: &Board, is_first: bool) -> i32 {
        EVAL_CALLS.fetch_add(1, Ordering::Relaxed);

        let player = board.player;
        let opp = opponent(player);
        let cache = &board.eval_cache;

        let territory = if player == FIRST_PLAYER {
            cache.owned_first - cache.owned_second
        } else {
            cache.owned_second - cache.owned_first
        };

        let mobility_score = 0i32;
        let connectivity = if player == FIRST_PLAYER {
            cache.connectivity_first - cache.connectivity_second
        } else {
            cache.connectivity_second - cache.connectivity_first
        };
        let corners = if player == FIRST_PLAYER {
            cache.corners_first - cache.corners_second
        } else {
            cache.corners_second - cache.corners_first
        };
        let edges = if player == FIRST_PLAYER {
            cache.edges_first - cache.edges_second
        } else {
            cache.edges_second - cache.edges_first
        };
        let recapture_swing = if opp == FIRST_PLAYER {
            cache.live_adjacent_first
        } else {
            cache.live_adjacent_second
        };
        let vulnerability = if player == FIRST_PLAYER {
            cache.live_adjacent_first
        } else {
            cache.live_adjacent_second
        };

        let weights = get_weights();
        let w = if is_first {
            weights.first
        } else {
            weights.second
        };
        territory * w.territory
            + mobility_score * w.mobility
            + connectivity * w.connectivity
            + corners * w.corners
            + edges * w.edges
            + recapture_swing * w.recapture
            - vulnerability * w.vulnerability
    }

    pub fn score_move(board: &Board, mv: &Move, is_first: bool) -> i32 {
        if mv.is_pass() {
            let mut copy = board.clone();
            copy.apply_pass();
            return evaluate(&copy, is_first);
        }
        let mut copy = board.clone();
        copy.apply_move(mv);
        evaluate(&copy, is_first)
    }
}

// --- src/opponent_db.rs ---
pub mod opponent_db {
    // opponent_db.rs — from opponent_db.hpp + opponent_db.cpp

    use std::sync::atomic::{AtomicPtr, AtomicU32, AtomicI32};
    use crate::types::*;

    // ====== Binary Format Constants ======

    const DB_MAGIC: u32 = 0x44415441;      // "DATA" LE
    const DB_FOOTER_MAGIC: u32 = 0x544144; // "DAT" reversed
    const DB_VERSION: u32 = 3;
    const DB_SECTION_FINGERPRINTS: u32 = 1;
    const DB_SECTION_CENTROIDS: u32 = 2;
    const DB_SECTION_PRIOR_CONFIGS: u32 = 3;
    const DB_SECTION_METADATA: u32 = 4;

    #[repr(C)]
    #[derive(Clone, Copy, Default, Debug)]
    struct DBHeader {
        magic: u32,
        version: u32,
        section_count: u32,
        crc32: u32,
        build_id: u64,
        baseline_id: u64,
        reserved: [u32; 2],
    }

    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    struct DBSection {
        stype: u32,
        count: u32,
        data_size: u32,
        reserved: u32,
    }

    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    struct DBFooter {
        magic: u32,
        total_size: u32,
    }

    #[repr(C)]
    #[derive(Clone, Copy, Default)]
    pub struct KnownFingerprint {
        pub id: u32,
        pub style: u32,    // KnownStyle as u32
        pub side_mask: u8, // bit0=FIRST, bit1=SECOND
        pub min_moves: u8,
        pub confidence_threshold: u8,
        pub margin_to_second: u8,
        pub mean: FeatureVector8,
        pub var: FeatureVector8,
        pub prior_config_id: u32,
    }

    #[derive(Clone, Default)]
    pub struct LoadedPriorConfig {
        pub id: u32,
        pub config: MovePriorConfig,
    }

    const MAX_FINGERPRINTS: usize = 16;
    const MAX_PRIOR_CONFIGS: usize = 16;

    pub struct OpponentDB {
        loaded: bool,
        data: Vec<u8>,
        header: DBHeader,
        fingerprints: [KnownFingerprint; MAX_FINGERPRINTS],
        fingerprint_count: usize,
        prior_configs: [Option<LoadedPriorConfig>; MAX_PRIOR_CONFIGS],
        prior_config_count: usize,
    }

    impl OpponentDB {
        pub fn new() -> Self {
            OpponentDB {
                loaded: false,
                data: Vec::new(),
                header: DBHeader::default(),
                fingerprints: [KnownFingerprint::default(); MAX_FINGERPRINTS],
                fingerprint_count: 0,
                prior_configs: Default::default(),
                prior_config_count: 0,
            }
        }

        pub fn load(&mut self, data: &[u8]) -> bool {
            let header_size = std::mem::size_of::<DBHeader>();
            let footer_size = std::mem::size_of::<DBFooter>();

            if data.len() < header_size + footer_size {
                eprintln!("OpponentDB: data too small ({} bytes)", data.len());
                return false;
            }

            self.data = data.to_vec();

            // Parse header
            self.header = unsafe {
                std::ptr::read_unaligned(self.data.as_ptr() as *const DBHeader)
            };

            if self.header.magic != DB_MAGIC || self.header.version != DB_VERSION {
                eprintln!(
                    "OpponentDB: bad magic/version (magic=0x{:X}, ver={})",
                    self.header.magic, self.header.version
                );
                self.loaded = false;
                return false;
            }

            if !self.validate_crc32() {
                eprintln!("OpponentDB: CRC mismatch");
                self.loaded = false;
                return false;
            }

            if !self.parse_sections() {
                self.loaded = false;
                return false;
            }

            self.loaded = true;
            true
        }

        pub fn load_from_file(&mut self, path: &str) -> bool {
            match std::fs::read(path) {
                Ok(buf) => self.load(&buf),
                Err(_) => {
                    eprintln!("OpponentDB: cannot open {}", path);
                    false
                }
            }
        }

        fn validate_crc32(&self) -> bool {
            let header_size = std::mem::size_of::<DBHeader>();
            let footer_size = std::mem::size_of::<DBFooter>();
            if header_size >= self.data.len() - footer_size {
                return false;
            }
            let crc_len = self.data.len() - header_size - footer_size;
            let expected = self.header.crc32;
            let actual = crc32_simple(&self.data[header_size..header_size + crc_len]);
            expected == actual
        }

        fn parse_sections(&mut self) -> bool {
            self.fingerprint_count = 0;
            self.prior_config_count = 0;

            let header_size = std::mem::size_of::<DBHeader>();
            let footer_size = std::mem::size_of::<DBFooter>();
            let section_size = std::mem::size_of::<DBSection>();
            let mut offset = header_size;

            for _ in 0..self.header.section_count {
                if offset + section_size > self.data.len() - footer_size {
                    return false;
                }
                let sec: DBSection = unsafe {
                    std::ptr::read_unaligned(self.data[offset..].as_ptr() as *const DBSection)
                };
                offset += section_size;

                if offset + sec.data_size as usize > self.data.len() - footer_size {
                    return false;
                }

                let sec_data = &self.data[offset..offset + sec.data_size as usize];

                match sec.stype {
                    DB_SECTION_FINGERPRINTS => {
                        let fp_size = std::mem::size_of::<KnownFingerprint>();
                        let count = (sec.data_size as usize / fp_size)
                            .min(MAX_FINGERPRINTS);
                        for i in 0..count {
                            self.fingerprints[self.fingerprint_count] = unsafe {
                                std::ptr::read_unaligned(
                                    sec_data[i * fp_size..].as_ptr() as *const KnownFingerprint
                                )
                            };
                            self.fingerprint_count += 1;
                        }
                    }
                    DB_SECTION_PRIOR_CONFIGS => {
                        let entry_size = 4 + std::mem::size_of::<MovePriorConfigRaw>();
                        let count = (sec.data_size as usize / entry_size)
                            .min(MAX_PRIOR_CONFIGS);
                        for i in 0..count {
                            let base = i * entry_size;
                            let id: u32 = unsafe {
                                std::ptr::read_unaligned(sec_data[base..].as_ptr() as *const u32)
                            };
                            let raw: MovePriorConfigRaw = unsafe {
                                std::ptr::read_unaligned(
                                    sec_data[base + 4..].as_ptr() as *const MovePriorConfigRaw
                                )
                            };
                            let cfg = MovePriorConfig {
                                shape_boost: raw.shape_boost,
                                medium_rect_boost: raw.medium_rect_boost,
                                barrier_boost: raw.barrier_boost,
                                connection_boost: raw.connection_boost,
                                dead_cell_risk_penalty: raw.dead_cell_risk_penalty,
                                side_boost_first: raw.side_boost_first,
                                side_boost_second: raw.side_boost_second,
                                max_total_adjustment: raw.max_total_adjustment,
                                confidence_min: raw.confidence_min,
                            };
                            let idx = self.prior_config_count;
                            self.prior_configs[idx] = Some(LoadedPriorConfig { id, config: cfg });
                            self.prior_config_count += 1;
                        }
                    }
                    DB_SECTION_CENTROIDS | DB_SECTION_METADATA => {
                        // Reserved
                    }
                    _ => {}
                }
                offset += sec.data_size as usize;
            }
            true
        }

        pub fn fingerprints(&self) -> &[KnownFingerprint] {
            &self.fingerprints[..self.fingerprint_count]
        }

        pub fn get_prior_config(&self, id: u32) -> Option<&MovePriorConfig> {
            for i in 0..self.prior_config_count {
                if let Some(ref lpc) = self.prior_configs[i] {
                    if lpc.id == id {
                        return Some(&lpc.config);
                    }
                }
            }
            None
        }

        pub fn default_prior_config(&self) -> Option<&MovePriorConfig> {
            if self.prior_config_count > 0 {
                if let Some(ref lpc) = self.prior_configs[0] {
                    return Some(&lpc.config);
                }
            }
            None
        }

        pub fn is_loaded(&self) -> bool {
            self.loaded
        }
    }

    // Raw C-layout struct matching the binary file format for MovePriorConfig
    #[repr(C)]
    #[derive(Clone, Copy)]
    struct MovePriorConfigRaw {
        shape_boost: [i16; 8],
        medium_rect_boost: i16,
        barrier_boost: i16,
        connection_boost: i16,
        dead_cell_risk_penalty: i16,
        side_boost_first: i16,
        side_boost_second: i16,
        max_total_adjustment: u16,
        confidence_min: u8,
        _pad: u8,
    }

    // Global instances
    use std::sync::{Mutex, OnceLock};

    static G_OPPONENT_DB_INNER: OnceLock<Mutex<OpponentDB>> = OnceLock::new();

    pub fn g_opponent_db() -> &'static Mutex<OpponentDB> {
        G_OPPONENT_DB_INNER.get_or_init(|| Mutex::new(OpponentDB::new()))
    }

    // Active prior config pointer (nullptr = no overhead when no data.bin)
    pub static G_ACTIVE_PRIOR_CONFIG: AtomicPtr<MovePriorConfig> =
        AtomicPtr::new(std::ptr::null_mut());

    // Current matched opponent style (for search engine to read)
    pub static G_MATCHED_STYLE: AtomicU32 = AtomicU32::new(0); // KnownStyle as u32
    pub static G_MATCH_CONFIDENCE: AtomicI32 = AtomicI32::new(0); // confidence * 100

    // CRC32 (nibble-by-nibble)
    fn crc32_simple(data: &[u8]) -> u32 {
        const TABLE: [u32; 16] = [
            0x00000000, 0x1DB71064, 0x3B6E20C8, 0x26D930AC,
            0x76DC4190, 0x6B6B51F4, 0x4DB26158, 0x5005713C,
            0xEDB88320, 0xF00F9344, 0xD6D6A3E8, 0xCB61B38C,
            0x9B64C2B0, 0x86D392D4, 0xA00AE278, 0xBDBDF21C,
        ];
        let mut crc: u32 = 0xFFFFFFFF;
        for &byte in data {
            crc ^= byte as u32;
            crc = TABLE[(crc & 0xF) as usize] ^ (crc >> 4);
            crc = TABLE[(crc & 0xF) as usize] ^ (crc >> 4);
        }
        !crc
    }

    // ====== OpponentFingerprint ======

    #[derive(Clone, Default)]
    pub struct OpponentFingerprint {
        pub move_count: i32,
        pub shape_counts: [i32; 8],
        pub total_area: i32,
        pub medium_count: i32,
        pub large_count: i32,
        pub tall_count: i32,
        pub wide_count: i32,
        pub region_counts: [i32; 4],
        pub steal_seen: i32,
        pub pass_seen: i32,
        pub first_pass_ply: i32,
        pub barrier_freq: i32,
        pub side_ply: i32,
        pub we_are_first: bool,
    }

    impl OpponentFingerprint {
        pub fn to_feature_vector(&self) -> FeatureVector8 {
            let mut fv = FeatureVector8::default();
            let n = self.move_count;
            if n == 0 {
                return fv;
            }
            let total = self.total_area;
            let medium = self.medium_count;
            let large = self.large_count;
            let tall = self.tall_count;
            let wide = self.wide_count;
            let steal = self.steal_seen;
            let pass = self.pass_seen;
            let barrier = self.barrier_freq;

            fv.dim[0] = ((total * 128) / n) as i16;
            fv.dim[1] = ((medium * 128) / n) as i16;
            fv.dim[2] = ((large * 128) / n) as i16;
            fv.dim[3] = ((tall * 128) / n) as i16;
            fv.dim[4] = ((wide * 128) / n) as i16;
            fv.dim[5] = ((steal * 128) / n) as i16;
            fv.dim[6] = ((pass * 128) / n) as i16;
            fv.dim[7] = ((barrier * 128) / n) as i16;
            fv
        }

        pub fn match_fingerprint(
            &self,
            fps: &[KnownFingerprint],
            out_confidence: &mut f32,
            out_margin: &mut f32,
        ) -> KnownStyle {
            *out_confidence = 0.0;
            *out_margin = 0.0;
            if fps.is_empty() || self.move_count == 0 {
                return KnownStyle::Unknown;
            }

            let fv = self.to_feature_vector();
            let mut best_idx: i32 = -1;
            let mut best_dist: f32 = 1e30;
            let mut second_dist: f32 = 1e30;

            // Per-dimension importance weights (steal/barrier/pass more discriminative)
            const DIM_WEIGHTS: [f32; 8] = [0.8, 1.0, 1.2, 1.0, 1.0, 1.5, 1.3, 1.4];

            for (i, fp) in fps.iter().enumerate() {
                let first_ok = (fp.side_mask & 1) != 0 && self.we_are_first;
                let second_ok = (fp.side_mask & 2) != 0 && !self.we_are_first;
                if !first_ok && !second_ok {
                    continue;
                }
                if self.move_count < fp.min_moves as i32 {
                    continue;
                }

                let mut dist = 0.0f32;
                for d in 0..8 {
                    let diff = (fv.dim[d] - fp.mean.dim[d]) as f32;
                    let inv_var = fp.var.dim[d] as f32;
                    let scaled = if inv_var > 0.0 {
                        diff / (inv_var / 128.0)
                    } else {
                        diff
                    };
                    dist += DIM_WEIGHTS[d] * scaled * scaled;
                }

                if dist < best_dist {
                    second_dist = best_dist;
                    best_dist = dist;
                    best_idx = i as i32;
                } else if dist < second_dist {
                    second_dist = dist;
                }
            }

            if best_idx < 0 {
                return KnownStyle::Unknown;
            }

            // Confidence: ratio-based
            if second_dist < 1e29 && second_dist > 0.01 {
                *out_confidence = 1.0 - (best_dist / second_dist);
            } else {
                // Single match: high confidence (no ambiguity with alternatives)
                *out_confidence = 0.95;
            }
            *out_margin = second_dist - best_dist;

            // Adaptive threshold: lower when we have more observations
            let best_fp = &fps[best_idx as usize];
            let base_threshold = best_fp.confidence_threshold as f32;
            let adaptive_threshold = if self.move_count >= 15 {
                base_threshold * 0.75
            } else if self.move_count >= 10 {
                base_threshold * 0.85
            } else {
                base_threshold
            };

            if (*out_confidence * 100.0) < adaptive_threshold {
                return KnownStyle::Unknown;
            }

            // Map u32 id to KnownStyle
            match best_fp.style {
                1 => KnownStyle::CordycepsAttack,
                2 => KnownStyle::CordycepsDefense,
                3 => KnownStyle::CordycepsBalanced,
                4 => KnownStyle::RustOld,
                5 => KnownStyle::RustUpdate,
                _ => KnownStyle::Unknown,
            }
        }
    }
}

// --- src/protocol.rs ---
pub mod protocol {
    // protocol.rs — from protocol.hpp + protocol.cpp

    use std::io::{BufRead, Write};
    use crate::board::Board;
    use crate::opponent_db::{g_opponent_db, G_ACTIVE_PRIOR_CONFIG, G_MATCHED_STYLE, G_MATCH_CONFIDENCE, OpponentFingerprint};
    use crate::search::{search_best_move, ensure_tt_ready};
    use crate::types::*;

    pub struct Protocol {
        board: Board,
        i_am_first: bool,
        running: bool,
        opp_consecutive_passes: i32,
        opp_passes_since_our_move: i32,
        // QR data.bin: passive opponent fingerprint
        opp_fp: OpponentFingerprint,
        move_counter: i32,
        opp_move_counter: i32,
        ply_counter: i32,
        matched_style: KnownStyle,
        match_confidence: f32,
        fingerprint_checked: bool,
        fingerprint_check_interval: i32,
        last_check_move: i32,
    }

    impl Protocol {
        fn activate_side_prior(&self) {
            let db = g_opponent_db().lock().unwrap();
            let preferred_id = if self.i_am_first { 1 } else { 2 };
            let selected = db
                .get_prior_config(preferred_id)
                .or_else(|| db.default_prior_config())
                .cloned();
            drop(db);

            if let Some(cfg) = selected {
                let raw = Box::into_raw(Box::new(cfg));
                G_ACTIVE_PRIOR_CONFIG.store(raw, std::sync::atomic::Ordering::Relaxed);
            } else {
                G_ACTIVE_PRIOR_CONFIG.store(std::ptr::null_mut(), std::sync::atomic::Ordering::Relaxed);
            }
        }

        pub fn new() -> Self {
            Protocol {
                board: Board::new(),
                i_am_first: false,
                running: true,
                opp_consecutive_passes: 0,
                opp_passes_since_our_move: 0,
                opp_fp: OpponentFingerprint::default(),
                move_counter: 0,
                opp_move_counter: 0,
                ply_counter: 0,
                matched_style: KnownStyle::Unknown,
                match_confidence: 0.0,
                fingerprint_checked: false,
                fingerprint_check_interval: 3,
                last_check_move: 0,
            }
        }

        pub fn run(&mut self) -> i32 {
            let stdin = std::io::stdin();
            let stdout = std::io::stdout();
            let mut out = stdout.lock();

            for line_res in stdin.lock().lines() {
                let line = match line_res {
                    Ok(l) => l.trim_end_matches('\r').to_string(),
                    Err(_) => break,
                };
                if line.is_empty() {
                    continue;
                }

                if line.starts_with("READY") {
                    self.handle_ready(&line, &mut out);
                } else if line.starts_with("INIT") {
                    self.handle_init(&line, &mut out);
                } else if line.starts_with("TIME") {
                    self.handle_time(&line, &mut out);
                } else if line.starts_with("OPP") {
                    self.handle_opp(&line);
                } else if line.starts_with("FINISH") {
                    self.log_shadow_metrics();
                    self.running = false;
                    break;
                }

                if !self.running {
                    break;
                }
            }
            0
        }

        fn write_line(out: &mut dyn Write, s: &str) {
            writeln!(out, "{}", s).ok();
            out.flush().ok();
        }

        fn handle_ready(&mut self, line: &str, out: &mut dyn Write) {
            if line.contains("FIRST") {
                self.i_am_first = true;
                self.board.player = FIRST_PLAYER;
            } else {
                self.i_am_first = false;
                self.board.player = SECOND_PLAYER;
            }
            self.activate_side_prior();
            Self::write_line(out, "OK");
        }

        fn handle_init(&mut self, line: &str, out: &mut dyn Write) {
            // Format: "INIT row1 row2 ... row10"
            let board_str = &line[5..]; // skip "INIT "
            self.board.init_from_string(board_str);
            self.opp_consecutive_passes = 0;
            ensure_tt_ready();

            // Reset fingerprint state per game
            self.opp_fp = OpponentFingerprint::default();
            self.move_counter = 0;
            self.opp_move_counter = 0;
            self.ply_counter = 0;
            self.matched_style = KnownStyle::Unknown;
            self.match_confidence = 0.0;
            self.fingerprint_checked = false;
            self.fingerprint_check_interval = 3;
            self.last_check_move = 0;
            self.activate_side_prior();

            // INIT doesn't output anything in the original protocol
            let _ = out;
        }

        fn handle_time(&mut self, line: &str, out: &mut dyn Write) {
            // Format: "TIME our_remaining opp_remaining"
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() < 3 {
                Self::write_line(out, "-1 -1 -1 -1");
                self.board.apply_pass();
                return;
            }
            let our_time: i32 = parts[1].parse().unwrap_or(0);
            let _opp_time: i32 = parts[2].parse().unwrap_or(0);

            self.opp_passes_since_our_move = 0;

            // Dynamic time budget
            let mut live = 0i32;
            for r in 0..ROWS {
                for c in 0..COLS {
                    if self.board.values[r][c] > 0 {
                        live += 1;
                    }
                }
            }
            let est_moves_left = std::cmp::max(4, live / 4);
            let mut time_budget = our_time / est_moves_left;
            if time_budget < 20 { time_budget = 20; }
            if time_budget > 2500 { time_budget = 2500; }

            // Edge: TIME after terminal
            if self.board.consecutive_passes >= 2 && self.opp_consecutive_passes < 2 {
                Self::write_line(out, "-1 -1 -1 -1");
                return;
            }

            // Opponent passed twice — lock win if ahead
            if self.opp_consecutive_passes >= 2 {
                let opp = opponent(self.board.player);
                let margin = self.board.owned_cells(self.board.player)
                    - self.board.owned_cells(opp);
                if margin > 0 {
                    Self::write_line(out, "-1 -1 -1 -1");
                    self.board.apply_pass();
                    return;
                }
            }

            self.move_counter += 1;
            self.ply_counter += 1;

            let mut best = search_best_move(&self.board, time_budget, self.i_am_first);
            if !best.is_pass() && !self.board.is_legal_move(&best) {
                let fallback = self.board.legal_moves();
                best = if fallback.is_empty() { PASS_MOVE } else { fallback[0] };
            }

            if best.is_pass() {
                Self::write_line(out, "-1 -1 -1 -1");
            } else {
                Self::write_line(
                    out,
                    &format!("{} {} {} {}", best.r1, best.c1, best.r2, best.c2),
                );
            }
            self.board.apply_move(&best);
        }

        fn handle_opp(&mut self, line: &str) {
            // Format: "OPP r1 c1 r2 c2 time_ms"
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() < 6 {
                return;
            }
            let r1: i32 = parts[1].parse().unwrap_or(-1);
            let c1: i32 = parts[2].parse().unwrap_or(-1);
            let r2: i32 = parts[3].parse().unwrap_or(-1);
            let c2: i32 = parts[4].parse().unwrap_or(-1);
            let opp_move = Move { r1, c1, r2, c2, priority: 0 };

            if opp_move.is_pass() {
                self.opp_consecutive_passes += 1;
                self.opp_passes_since_our_move += 1;
                // Only apply first opp pass since our move; second+ = Always Pass artifact
                if self.opp_passes_since_our_move <= 1 {
                    self.board.apply_move(&opp_move);
                }
            } else {
                // Measure steal BEFORE apply
                let mut steal_before = 0i32;
                for r in opp_move.r1..=opp_move.r2 {
                    for c in opp_move.c1..=opp_move.c2 {
                        if self.board.owners[r as usize][c as usize] == self.board.player {
                            steal_before += 1;
                        }
                    }
                }
                self.opp_consecutive_passes = 0;
                self.opp_passes_since_our_move = 0;
                self.board.apply_move(&opp_move);
                if steal_before > 0 {
                    self.opp_fp.steal_seen += 1;
                }
            }

            self.ply_counter += 1;

            if !opp_move.is_pass() {
                self.opp_move_counter += 1;
                self.opp_fp.move_count = self.opp_move_counter;
                self.opp_fp.side_ply = self.ply_counter;
                self.opp_fp.we_are_first = self.i_am_first;

                let area = move_area(opp_move.r1, opp_move.c1, opp_move.r2, opp_move.c2);
                self.opp_fp.total_area += area;
                let sc = classify_shape(opp_move.r1, opp_move.c1, opp_move.r2, opp_move.c2) as usize;
                self.opp_fp.shape_counts[sc] += 1;
                if area >= 5 && area <= 10 { self.opp_fp.medium_count += 1; }
                if area >= 11 { self.opp_fp.large_count += 1; }

                let orient = classify_orientation(opp_move.r1, opp_move.c1, opp_move.r2, opp_move.c2);
                if orient == Orientation::Portrait { self.opp_fp.tall_count += 1; }
                if orient == Orientation::Landscape { self.opp_fp.wide_count += 1; }

                let rt = classify_region(opp_move.r1, opp_move.c1, opp_move.r2, opp_move.c2);
                if rt != RegionTag::None {
                    self.opp_fp.region_counts[rt as usize] += 1;
                }

                if self.board.barrier_potential(opp_move.r1, opp_move.c1, opp_move.r2, opp_move.c2) > 0 {
                    self.opp_fp.barrier_freq += 1;
                }
            } else {
                self.opp_fp.pass_seen += 1;
                if self.opp_fp.first_pass_ply == 0 {
                    self.opp_fp.first_pass_ply = self.ply_counter;
                }
            }

            // Try to match known fingerprint after sufficient observations
            // Re-check periodically to improve accuracy as more data accumulates
            let should_check = if !self.fingerprint_checked && self.opp_move_counter >= 5 {
                true
            } else if self.fingerprint_checked
                && self.opp_move_counter >= self.last_check_move + self.fingerprint_check_interval
                && self.match_confidence < 0.80
            {
                true
            } else {
                false
            };

            if should_check {
                    let db = g_opponent_db().lock().unwrap();
                let fps = db.fingerprints();
                let mut conf = 0.0f32;
                let mut margin = 0.0f32;
                let style = self.opp_fp.match_fingerprint(fps, &mut conf, &mut margin);

                if style != KnownStyle::Unknown && conf >= 0.40 {
                    let old_style = self.matched_style;
                    self.matched_style = style;
                    self.match_confidence = conf;
                    self.fingerprint_checked = true;
                    self.last_check_move = self.opp_move_counter;

                    // Update globals for search engine
                    G_MATCHED_STYLE.store(style as u32, std::sync::atomic::Ordering::Relaxed);
                    G_MATCH_CONFIDENCE.store((conf * 100.0) as i32, std::sync::atomic::Ordering::Relaxed);

                    // Only update prior config if style changed or first match
                    if old_style != style || !self.fingerprint_checked {
                        // Select style-specific counter prior config
                        for fp in fps {
                            let fp_style = match fp.style {
                                1 => KnownStyle::CordycepsAttack,
                                2 => KnownStyle::CordycepsDefense,
                                3 => KnownStyle::CordycepsBalanced,
                                4 => KnownStyle::RustOld,
                                5 => KnownStyle::RustUpdate,
                                _ => KnownStyle::Unknown,
                            };
                            if fp_style == style {
                                if let Some(cfg) = db.get_prior_config(fp.prior_config_id) {
                                    // Leak a Box to get a 'static pointer — small, lives for program lifetime
                                    let boxed = Box::new(cfg.clone());
                                    let raw = Box::into_raw(boxed);
                                    G_ACTIVE_PRIOR_CONFIG.store(
                                        raw,
                                        std::sync::atomic::Ordering::Relaxed,
                                    );
                                }
                                break;
                            }
                        }
                    }
                } else if self.fingerprint_checked {
                    // Update last_check_move even if no new match
                    self.last_check_move = self.opp_move_counter;
                }
            }
        }

        fn log_shadow_metrics(&self) {
            #[cfg(not(feature = "online_judge"))]
            {
                static GAME_COUNT: std::sync::atomic::AtomicI32 =
                    std::sync::atomic::AtomicI32::new(0);
                let game = GAME_COUNT.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;

                let fv = self.opp_fp.to_feature_vector();
                let side = if self.i_am_first { "FIRST" } else { "SECOND" };
                let style = match self.matched_style {
                    KnownStyle::CordycepsAttack => "CORDYCEPS_ATTACK",
                    KnownStyle::CordycepsDefense => "CORDYCEPS_DEFENSE",
                    KnownStyle::CordycepsBalanced => "CORDYCEPS_BALANCED",
                    KnownStyle::RustOld => "RUST_OLD",
                    KnownStyle::RustUpdate => "RUST_UPDATE",
                    KnownStyle::Unknown => "UNKNOWN",
                };
                if let Ok(mut f) = std::fs::OpenOptions::new()
                    .create(true)
                    .append(true)
                    .open("fingerprint_shadow.log")
                {
                    writeln!(
                        f,
                        "G{} {} moves={} opp_moves={} matched={} conf={:.2} \
                         fv=[{},{},{},{},{},{},{},{}] ply={}",
                        game, side, self.move_counter, self.opp_move_counter,
                        style, self.match_confidence,
                        fv.dim[0], fv.dim[1], fv.dim[2], fv.dim[3],
                        fv.dim[4], fv.dim[5], fv.dim[6], fv.dim[7],
                        self.ply_counter
                    ).ok();
                }
            }
        }
    }
}

// --- src/search ---
pub mod search {
    pub mod ordering {
        use crate::types::*;

        use super::tt::pack_move;

        // ====== Move Ordering ======

        pub(super) fn order_moves(
            moves: &mut Vec<Move>,
            pv_move: &Move,
            depth: i32,
            killers: &[[u32; 2]; 64],
            history: &[[i32; COLS]; ROWS],
            killer_history_on: bool,
        ) {
            if killer_history_on && depth >= 0 && depth < 64 {
                let d = depth as usize;
                for m in moves.iter_mut() {
                    let pm = pack_move(m);
                    if pm == killers[d][0] {
                        m.priority += 9000;
                    } else if pm == killers[d][1] {
                        m.priority += 8000;
                    } else {
                        let h = history[m.r2 as usize][m.c2 as usize];
                        if h > 0 { m.priority += h * 10; }
                    }
                }
            }
            let pv = *pv_move;
            moves.sort_unstable_by(|a, b| {
                let a_pv = a.coords_eq(&pv);
                let b_pv = b.coords_eq(&pv);
                if a_pv && !b_pv { return std::cmp::Ordering::Less; }
                if b_pv && !a_pv { return std::cmp::Ordering::Greater; }
                b.priority.cmp(&a.priority)
            });
        }
    }

    pub mod tt {
        use std::sync::atomic::{AtomicU64, AtomicU8, Ordering};
        use std::cell::UnsafeCell;
        use std::sync::OnceLock;

        use crate::types::*;

        // ====== Transposition Table ======

        pub const TT_SIZE: usize = 1 << 22;

        #[derive(Clone, Copy, Default)]
        pub struct CompactTTEntry {
            pub key_sig: u32,
            pub depth: i16,
            pub flag: u8,
            pub age: u8,
            pub value: i32,
            pub packed_move: u32,
        }

        #[derive(Clone, Copy, Default)]
        pub struct TTBucket {
            pub slot0: CompactTTEntry,
            pub slot1: CompactTTEntry,
        }

        pub mod tt_flag {
            pub const EMPTY: u8 = 0;
            pub const EXACT: u8 = 1;
            pub const LOWER_BOUND: u8 = 2;
            pub const UPPER_BOUND: u8 = 3;
        }

        pub static NODES_SEARCHED: AtomicU64 = AtomicU64::new(0);

        struct SingleThreadTT(UnsafeCell<Vec<TTBucket>>);

        unsafe impl Sync for SingleThreadTT {}

        static TT: OnceLock<SingleThreadTT> = OnceLock::new();

        static TT_AGE: AtomicU8 = AtomicU8::new(1);

        pub fn ensure_tt_ready() {
            let tt = TT.get_or_init(|| SingleThreadTT(UnsafeCell::new(Vec::new())));
            let tt = unsafe { &mut *tt.0.get() };
            if tt.len() != TT_SIZE {
                tt.resize(TT_SIZE, TTBucket::default());
            }
        }

        pub fn pack_move(m: &Move) -> u32 {
            if m.is_pass() {
                return 0xFFFFFFFF;
            }
            ((m.r1 as u32 & 0xF) << 15)
                | ((m.c1 as u32 & 0x1F) << 10)
                | ((m.r2 as u32 & 0xF) << 6)
                | ((m.c2 as u32 & 0x1F) << 1)
        }

        pub fn unpack_move(packed: u32) -> Move {
            if packed == 0xFFFFFFFF {
                return PASS_MOVE;
            }
            Move {
                r1: ((packed >> 15) & 0xF) as i32,
                c1: ((packed >> 10) & 0x1F) as i32,
                r2: ((packed >> 6) & 0xF) as i32,
                c2: ((packed >> 1) & 0x1F) as i32,
                priority: 0,
            }
        }

        pub fn tt_store(key: u64, depth: i32, value: i32, flag: u8, best_move: &Move) {
            let age = TT_AGE.load(Ordering::Relaxed);
            let ksig = (key >> 32) as u32;
            let idx = (key as usize) & (TT_SIZE - 1);
            let pm = pack_move(best_move);
            let d16 = depth as i16;

            let tt = TT.get_or_init(|| SingleThreadTT(UnsafeCell::new(Vec::new())));
            let tt = unsafe { &mut *tt.0.get() };
            let b = &mut tt[idx];

            b.slot0 = CompactTTEntry { key_sig: ksig, depth: d16, flag, age, value, packed_move: pm };

            let same_key = b.slot1.key_sig == ksig;
            let stale = b.slot1.age != age;
            let deeper = depth >= b.slot1.depth as i32;
            let replace = if same_key { deeper } else { stale || deeper };
            if replace {
                b.slot1 = CompactTTEntry { key_sig: ksig, depth: d16, flag, age, value, packed_move: pm };
            }
        }

        pub fn tt_probe(
            key: u64,
            depth: i32,
            alpha: i32,
            beta: i32,
            value_out: &mut i32,
            best_move_out: &mut Move,
        ) -> bool {
            let ksig = (key >> 32) as u32;
            let idx = (key as usize) & (TT_SIZE - 1);
            let tt = TT.get_or_init(|| SingleThreadTT(UnsafeCell::new(Vec::new())));
            let tt = unsafe { &*tt.0.get() };
            let b = &tt[idx];

            let mut best: Option<CompactTTEntry> = None;
            if b.slot0.key_sig == ksig && b.slot0.depth >= depth as i16 {
                best = Some(b.slot0);
            }
            if b.slot1.key_sig == ksig && b.slot1.depth >= depth as i16 {
                if best.is_none() || b.slot1.depth > best.unwrap().depth {
                    best = Some(b.slot1);
                }
            }

            let entry = match best {
                None => return false,
                Some(e) => e,
            };

            *best_move_out = unpack_move(entry.packed_move);
            let stored = entry.value;

            if entry.flag == tt_flag::EXACT { *value_out = stored; return true; }
            if entry.flag == tt_flag::LOWER_BOUND && stored >= beta { *value_out = stored; return true; }
            if entry.flag == tt_flag::UPPER_BOUND && stored <= alpha { *value_out = stored; return true; }
            false
        }

        pub fn advance_tt_age() {
            TT_AGE.fetch_add(1, Ordering::Relaxed);
        }
    }

    pub mod zobrist {
        use crate::board::Board;
        use crate::types::*;

        // ====== Zobrist Hashing ======
        // Single sequential seed matching C++ exactly

        fn xorshift64(state: &mut u64) -> u64 {
            *state ^= *state << 13;
            *state ^= *state >> 7;
            *state ^= *state << 17;
            *state
        }

        struct ZobristTables {
            value: [[[u64; 10]; COLS]; ROWS],
            owner: [[[u64; 3]; COLS]; ROWS],
            player: u64,
            passes: [u64; 3],
        }

        static ZOBRIST: std::sync::OnceLock<ZobristTables> = std::sync::OnceLock::new();

        fn get_zobrist() -> &'static ZobristTables {
            ZOBRIST.get_or_init(|| {
                let mut seed = 1234567890123456789u64;
                let mut value = [[[0u64; 10]; COLS]; ROWS];
                for r in 0..ROWS {
                    for c in 0..COLS {
                        for v in 0..10 {
                            value[r][c][v] = xorshift64(&mut seed);
                        }
                    }
                }
                let mut owner = [[[0u64; 3]; COLS]; ROWS];
                for r in 0..ROWS {
                    for c in 0..COLS {
                        for o in 0..3 {
                            owner[r][c][o] = xorshift64(&mut seed);
                        }
                    }
                }
                let player = xorshift64(&mut seed);
                let mut passes = [0u64; 3];
                for i in 0..3 {
                    passes[i] = xorshift64(&mut seed);
                }
                ZobristTables { value, owner, player, passes }
            })
        }

        pub(crate) fn cell_hash(r: usize, c: usize, value: i8, owner: i8) -> u64 {
            let z = get_zobrist();
            let mut h = 0u64;
            let v = value as usize;
            if v > 0 && v <= 9 {
                h ^= z.value[r][c][v];
            }
            let oi = if owner == FIRST_PLAYER { 1usize }
                     else if owner == SECOND_PLAYER { 2usize }
                     else { 0usize };
            h ^ z.owner[r][c][oi]
        }

        pub(crate) fn player_hash(player: i8) -> u64 {
            if player == FIRST_PLAYER {
                get_zobrist().player
            } else {
                0
            }
        }

        pub(crate) fn passes_hash(consecutive_passes: i32) -> u64 {
            if (0..=2).contains(&consecutive_passes) {
                get_zobrist().passes[consecutive_passes as usize]
            } else {
                0
            }
        }

        pub fn hash_board(board: &Board) -> u64 {
            let z = get_zobrist();
            let mut h = 0u64;
            for r in 0..ROWS {
                for c in 0..COLS {
                    let v = board.values[r][c] as usize;
                    if v > 0 && v <= 9 {
                        h ^= z.value[r][c][v];
                    }
                    let o = board.owners[r][c];
                    let oi = if o == FIRST_PLAYER { 1usize }
                             else if o == SECOND_PLAYER { 2usize }
                             else { 0usize };
                    h ^= z.owner[r][c][oi];
                }
            }
            if board.player == FIRST_PLAYER {
                h ^= z.player;
            }
            let cp = board.consecutive_passes as usize;
            if cp <= 2 {
                h ^= z.passes[cp];
            }
            h
        }
    }

    pub mod engine {
        use std::sync::atomic::Ordering;
        use std::time::Instant;

        use crate::board::{Board, MoveRecord};
        use crate::eval::evaluate;
        use crate::types::*;

        use super::ordering::order_moves;
        use super::tt::{advance_tt_age, ensure_tt_ready, pack_move, tt_flag, tt_probe, tt_store, NODES_SEARCHED};

        // ====== Search Context ======

        struct SearchCtx {
            start: Instant,
            budget_ms: i64,
            is_first: bool,
            killer_history_on: bool,
            nullmove_on: bool,
            pass_mode: i32,
            pass_fix: i32,
            killers: [[u32; 2]; 64],
            history: [[i32; COLS]; ROWS],
            nullmove_ok: bool,
        }

        impl SearchCtx {
            fn timed_out(&self) -> bool {
                self.start.elapsed().as_millis() as i64 >= self.budget_ms
            }

            fn elapsed_ms(&self) -> i64 {
                self.start.elapsed().as_millis() as i64
            }
        }

        fn should_try_pass(board: &Board, ctx: &SearchCtx) -> bool {
            if ctx.pass_mode == 1 {
                return true;
            }
            if ctx.pass_mode == 2 {
                return false;
            }
            if ctx.pass_fix != 0 {
                let p = board.player;
                let opp = opponent(p);
                return board.owned_cells(p) - board.owned_cells(opp) > 0;
            }
            evaluate(board, ctx.is_first) > 0
        }

        #[derive(Clone, Copy, Debug, Default)]
        pub struct SearchReport {
            pub best_move: Move,
            pub completed_depth: i32,
            pub nodes: u64,
            pub elapsed_ms: i64,
        }

        fn apply_second_root_biases(board: &mut Board, moves: &mut [Move], is_first: bool, second_steal: i32) {
            apply_second_defensive_biases(board, moves, is_first, second_steal, true);
        }

        fn immediate_recapture_pressure(board: &Board) -> i32 {
            let opp_moves = board.legal_moves();
            let mut best_steal = 0i32;
            for mv in &opp_moves {
                if mv.is_pass() {
                    continue;
                }
                let mut steal = 0i32;
                for r in mv.r1..=mv.r2 {
                    for c in mv.c1..=mv.c2 {
                        if board.owners[r as usize][c as usize] == opponent(board.player) {
                            steal += 1;
                        }
                    }
                }
                if steal > best_steal {
                    best_steal = steal;
                }
            }
            best_steal
        }

        fn apply_second_defensive_biases(
            board: &mut Board,
            moves: &mut [Move],
            is_first: bool,
            second_steal: i32,
            include_static_eval: bool,
        ) {
            if is_first {
                return;
            }

            let opp_p = opponent(board.player);
            let claimed_cells = board.owned_cells(FIRST_PLAYER) + board.owned_cells(SECOND_PLAYER);
            let opening_phase = claimed_cells < 24;
            let midgame_phase = claimed_cells < 70;
            for m in moves.iter_mut() {
                if m.is_pass() {
                    m.priority -= 2000;
                    continue;
                }

                let mut steal = 0i32;
                let area = (m.r2 - m.r1 + 1) * (m.c2 - m.c1 + 1);
                for r in m.r1..=m.r2 {
                    for c in m.c1..=m.c2 {
                        let ru = r as usize;
                        let cu = c as usize;
                        if board.owners[ru][cu] != opp_p {
                            continue;
                        }
                        let mut adjacent_live = false;
                        if r > 0 && board.values[ru - 1][cu] > 0 {
                            adjacent_live = true;
                        } else if r < ROWS as i32 - 1 && board.values[ru + 1][cu] > 0 {
                            adjacent_live = true;
                        } else if c > 0 && board.values[ru][cu - 1] > 0 {
                            adjacent_live = true;
                        } else if c < COLS as i32 - 1 && board.values[ru][cu + 1] > 0 {
                            adjacent_live = true;
                        }
                        if adjacent_live {
                            steal += 1;
                        }
                    }
                }

                let connection = board.connectivity_boost(m.r1, m.c1, m.r2, m.c2);
                let risk = board.dead_cell_risk_proxy(m.r1, m.c1, m.r2, m.c2);
                let barrier = board.barrier_potential(m.r1, m.c1, m.r2, m.c2);
                let compact_bonus = if area <= 4 {
                    140
                } else if area >= 8 {
                    -100
                } else {
                    40
                };
                let counter_bonus = if steal > 0 {
                    if opening_phase { steal * 85 } else { steal * 60 }
                } else {
                    0
                };
                let connection_bonus = if opening_phase { connection * 32 } else { connection * 22 };
                let risk_penalty = if opening_phase { risk * 85 } else { risk * 52 };
                let barrier_bonus = if opening_phase { barrier * 180 } else { barrier * 110 };
                let extension_penalty = if steal == 0 && area >= 7 { 140 } else { 0 };
                let loose_shape_penalty = if connection == 0 && risk > 0 { 120 } else { 0 };
                let quiet_opening_penalty = if opening_phase && steal == 0 && barrier == 0 {
                    area * 8
                } else {
                    0
                };
                let midgame_guard_bonus = if midgame_phase && connection > 0 && risk == 0 { 90 } else { 0 };
                let mut recapture_tiebreak = 0;

                m.priority += counter_bonus;
                if second_steal != 0 {
                    m.priority += steal * 30;
                }
                m.priority += connection_bonus;
                m.priority -= risk_penalty;
                m.priority += barrier_bonus;
                m.priority += compact_bonus;
                m.priority += midgame_guard_bonus;
                m.priority -= extension_penalty;
                m.priority -= loose_shape_penalty;
                m.priority -= quiet_opening_penalty;

                if include_static_eval {
                    let mut rec = MoveRecord::new();
                    board.make_move(m, &mut rec);
                    if opening_phase {
                        let recapture = immediate_recapture_pressure(board);
                        recapture_tiebreak = recapture * 8;
                    }
                    let static_score = -evaluate(board, is_first);
                    board.unmake_move(&rec);
                    m.priority += static_score / 12;
                }
                m.priority -= recapture_tiebreak;
            }
        }

        // ====== Alpha-Beta ======

        fn alpha_beta(
            board: &mut Board,
            depth: i32,
            mut alpha: i32,
            beta: i32,
            ctx: &mut SearchCtx,
            best_move_out: &mut Move,
        ) -> i32 {
            if board.consecutive_passes >= 2 {
                let p = board.player;
                let opp = opponent(p);
                let margin = board.owned_cells(p) - board.owned_cells(opp);
                return if margin > 0 { 100000 + margin }
                       else if margin < 0 { -100000 + margin }
                       else { 0 };
            }

            let nc = NODES_SEARCHED.load(Ordering::Relaxed);
            if (nc & 4095) == 0 && ctx.timed_out() {
                return evaluate(board, ctx.is_first);
            }
            NODES_SEARCHED.fetch_add(1, Ordering::Relaxed);

            if depth == 0 {
                return evaluate(board, ctx.is_first);
            }

            let key = board.hash;
            let mut tt_value = 0i32;
            let mut tt_move = PASS_MOVE;
            if tt_probe(key, depth, alpha, beta, &mut tt_value, &mut tt_move) {
                *best_move_out = tt_move;
                return tt_value;
            }

            if ctx.nullmove_on && depth >= 3 && !ctx.nullmove_ok {
                ctx.nullmove_ok = true;
            }
            if ctx.nullmove_on && depth >= 3 && ctx.nullmove_ok && alpha == beta - 1 {
                let static_eval = evaluate(board, ctx.is_first);
                if static_eval >= beta {
                    let mut rec = MoveRecord::new();
                    board.make_move(&PASS_MOVE, &mut rec);
                    ctx.nullmove_ok = false;
                    let mut dummy = PASS_MOVE;
                    let score = -alpha_beta(board, depth - 4, -beta, -beta + 1, ctx, &mut dummy);
                    ctx.nullmove_ok = true;
                    board.unmake_move(&rec);
                    if score >= beta {
                        *best_move_out = PASS_MOVE;
                        return score;
                    }
                }
            }

            let mut moves = board.legal_moves();

            if moves.is_empty() {
                let mut rec = MoveRecord::new();
                board.make_move(&PASS_MOVE, &mut rec);
                let mut dummy = PASS_MOVE;
                let score = -alpha_beta(board, depth - 1, -beta, -alpha, ctx, &mut dummy);
                board.unmake_move(&rec);
                return score;
            }

            if !ctx.is_first && depth <= 3 {
                apply_second_defensive_biases(board, &mut moves, false, 0, false);
            }

            let killers = ctx.killers;
            let history = ctx.history;
            order_moves(&mut moves, &tt_move, depth, &killers, &history, ctx.killer_history_on);

            let mut best_value = -999999i32;
            let mut local_best = moves[0];
            let mut flag = tt_flag::UPPER_BOUND;

            for mv in &moves {
                let mut rec = MoveRecord::new();
                board.make_move(mv, &mut rec);
                let mut dummy = PASS_MOVE;
                let score = -alpha_beta(board, depth - 1, -beta, -alpha, ctx, &mut dummy);
                board.unmake_move(&rec);

                if score > best_value {
                    best_value = score;
                    local_best = *mv;
                }
                if score > alpha {
                    alpha = score;
                    flag = tt_flag::EXACT;
                }
                if alpha >= beta {
                    flag = tt_flag::LOWER_BOUND;
                    if ctx.killer_history_on && depth < 64 && !mv.is_pass() {
                        let d = depth as usize;
                        let pm = pack_move(mv);
                        if pm != ctx.killers[d][0] {
                            ctx.killers[d][1] = ctx.killers[d][0];
                            ctx.killers[d][0] = pm;
                        }
                        ctx.history[mv.r2 as usize][mv.c2 as usize] += 1;
                    }
                    break;
                }
            }

            if ctx.pass_mode != 2 && depth >= 3 && moves.len() <= 5 {
                let try_pass = should_try_pass(board, ctx);

                if try_pass {
                    let mut rec = MoveRecord::new();
                    board.make_move(&PASS_MOVE, &mut rec);
                    let mut dummy = PASS_MOVE;
                    let pass_score = -alpha_beta(board, depth - 1, -beta, -alpha, ctx, &mut dummy);
                    board.unmake_move(&rec);
                    if pass_score > best_value {
                        best_value = pass_score;
                        local_best = PASS_MOVE;
                        flag = tt_flag::EXACT;
                    }
                }
            }

            *best_move_out = local_best;
            tt_store(key, depth, best_value, flag, &local_best);
            best_value
        }

        // ====== Iterative Deepening ======

        pub fn search_best_move(board: &Board, time_budget_ms: i32, is_first: bool) -> Move {
            search_best_move_report(board, time_budget_ms, is_first).best_move
        }

        pub fn search_best_move_report(board: &Board, time_budget_ms: i32, is_first: bool) -> SearchReport {
            NODES_SEARCHED.store(0, Ordering::Relaxed);
            ensure_tt_ready();

            let killer_history_on = std::env::var("KILLER_HISTORY")
                .ok().and_then(|v| v.parse::<i32>().ok()).map(|v| v > 0).unwrap_or(true);
            let nullmove_on = std::env::var("NULLMOVE")
                .ok().and_then(|v| v.parse::<i32>().ok()).map(|v| v > 0).unwrap_or(false);
            let asp_window: i32 = match std::env::var("ASP_WINDOW").as_deref() {
                Ok("0") | Ok("full") => 0,
                Ok("adaptive") => -1,
                Ok(s) => s.parse().unwrap_or(50),
                Err(_) => 50,
            };
            let pass_mode: i32 = match std::env::var("PASS_MODE").as_deref() {
                Ok("no-gate") => 1,
                Ok("none") => 2,
                _ => 0,
            };
            let pass_fix: i32 = std::env::var("PASS_FIX")
                .ok().and_then(|v| v.parse().ok()).unwrap_or(0);
            let second_steal: i32 = std::env::var("SECOND_STEAL")
                .ok().and_then(|v| v.parse().ok()).unwrap_or(0);

            advance_tt_age();

            let budget = std::cmp::max(1i64, time_budget_ms as i64 * 80 / 100);

            let mut work_board = board.clone();
            let mut moves = work_board.legal_moves();
            if moves.is_empty() {
                return SearchReport {
                    best_move: PASS_MOVE,
                    completed_depth: 0,
                    nodes: NODES_SEARCHED.load(Ordering::Relaxed),
                    elapsed_ms: 0,
                };
            }

            let empty_killers = [[0u32; 2]; 64];
            let empty_history = [[0i32; COLS]; ROWS];
            order_moves(&mut moves, &PASS_MOVE, 0, &empty_killers, &empty_history, killer_history_on);
            apply_second_root_biases(&mut work_board, &mut moves, is_first, second_steal);
            order_moves(&mut moves, &PASS_MOVE, 0, &empty_killers, &empty_history, killer_history_on);

            let mut best_move = moves[0];
            let max_depth = 12i32;
            let search_start = Instant::now();
            let mut completed_depth = 0i32;

            if moves.len() <= 5 {
                let mut ctx = SearchCtx {
                    start: search_start,
                    budget_ms: budget,
                    is_first,
                    killer_history_on,
                    nullmove_on,
                    pass_mode,
                    pass_fix,
                    killers: [[0u32; 2]; 64],
                    history: [[0i32; COLS]; ROWS],
                    nullmove_ok: true,
                };
                let mut endgame_best = best_move;
                alpha_beta(&mut work_board, 8, -999999, 999999, &mut ctx, &mut endgame_best);
                if !ctx.timed_out() {
                    return SearchReport {
                        best_move: endgame_best,
                        completed_depth: 8,
                        nodes: NODES_SEARCHED.load(Ordering::Relaxed),
                        elapsed_ms: search_start.elapsed().as_millis() as i64,
                    };
                }
                best_move = endgame_best;
            }

            let mut prev_score = 0i32;
            let mut first_iteration = true;

            let mut ctx = SearchCtx {
                start: search_start,
                budget_ms: budget,
                is_first,
                killer_history_on,
                nullmove_on,
                pass_mode,
                pass_fix,
                killers: [[0u32; 2]; 64],
                history: [[0i32; COLS]; ROWS],
                nullmove_ok: true,
            };

            for depth in 1..=max_depth {
                let depth_start_ms = ctx.elapsed_ms();
                let mut depth_best = best_move;
                let score;

                if first_iteration || asp_window == 0 {
                    score = alpha_beta(&mut work_board, depth, -999999, 999999, &mut ctx, &mut depth_best);
                    first_iteration = false;
                } else {
                    let w = if asp_window == -1 {
                        std::cmp::max(200, prev_score.abs() / 4)
                    } else {
                        asp_window
                    };
                    let a = prev_score - w;
                    let b_val = prev_score + w;
                    let s = alpha_beta(&mut work_board, depth, a, b_val, &mut ctx, &mut depth_best);
                    if s <= a || s >= b_val {
                        score = alpha_beta(&mut work_board, depth, -999999, 999999, &mut ctx, &mut depth_best);
                    } else {
                        score = s;
                    }
                }

                if !ctx.timed_out() {
                    best_move = depth_best;
                    prev_score = score;
                    completed_depth = depth;
                }

                let depth_elapsed = ctx.elapsed_ms() - depth_start_ms;
                if ctx.timed_out() || depth_elapsed > budget / 2 {
                    break;
                }
            }

            SearchReport {
                best_move,
                completed_depth,
                nodes: NODES_SEARCHED.load(Ordering::Relaxed),
                elapsed_ms: search_start.elapsed().as_millis() as i64,
            }
        }
    }


    pub use engine::{search_best_move, search_best_move_report, SearchReport};
    pub use tt::ensure_tt_ready;
    pub use zobrist::hash_board;
}

// --- src/main.rs ---
// main.rs — from main.cpp

use crate::opponent_db::g_opponent_db;
use crate::protocol::Protocol;

// Embedded data.bin: place your data.bin bytes here if needed.
// Build with feature "embedded_data" to activate, or let it fall back to file.
#[cfg(feature = "embedded_data")]
const EMBEDDED_DATA_BIN: &[u8] = include_bytes!("../data.bin");

#[cfg(not(feature = "embedded_data"))]
const EMBEDDED_DATA_BIN: &[u8] = &[];

fn main() {
    // Load data.bin: try embedded first, then file
    if !EMBEDDED_DATA_BIN.is_empty() {
        let mut db = g_opponent_db().lock().unwrap();
        db.load(EMBEDDED_DATA_BIN);
    } else {
        let mut db = g_opponent_db().lock().unwrap();
        db.load_from_file("data.bin");
    }

    let mut protocol = Protocol::new();
    std::process::exit(protocol.run());
}
