import os
import re

SRC_DIR = "src"
OUTPUT_FILE = "submission.rs"

FLAT_MODULES = [
    ("types", "types.rs"),
    ("timer", "timer.rs"),
    ("board", "board.rs"),
    ("movegen", "movegen.rs"),
    ("eval", "eval.rs"),
    ("opponent_db", "opponent_db.rs"),
    ("protocol", "protocol.rs"),
]

SEARCH_CHILDREN = [
    ("ordering", "ordering.rs"),
    ("tt", "tt.rs"),
    ("zobrist", "zobrist.rs"),
    ("engine", "engine.rs"),
]

SEARCH_MOD_LINES_TO_DROP = {
    "mod engine;",
    "mod ordering;",
    "mod tt;",
    "mod zobrist;",
    "pub(crate) mod zobrist;",
}


def indent_content(content: str, indent: str = "    ") -> str:
    return "\n".join(indent + line if line.strip() else "" for line in content.splitlines())


def read_file(path: str, remove_patterns=None) -> str:
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    if remove_patterns:
        for pattern in remove_patterns:
            content = re.sub(pattern, "", content)
    return content.rstrip()


lines = [
    "// Generated by merge.py",
    "// Do not edit by hand; edit src/ instead.",
    "#![allow(dead_code, unused_imports)]",
    "",
]

# Flat modules from src/*.rs
for mod_name, filename in FLAT_MODULES:
    path = os.path.join(SRC_DIR, filename)
    if not os.path.exists(path):
        continue
    lines.append(f"// --- src/{filename} ---")
    lines.append(f"pub mod {mod_name} {{")
    lines.append(indent_content(read_file(path)))
    lines.append("}")
    lines.append("")

# src/search/*.rs
search_dir = os.path.join(SRC_DIR, "search")
if os.path.exists(search_dir):
    lines.append("// --- src/search ---")
    lines.append("pub mod search {")

    for mod_name, filename in SEARCH_CHILDREN:
        path = os.path.join(search_dir, filename)
        if not os.path.exists(path):
            continue
        lines.append(f"    pub mod {mod_name} {{")
        lines.append(indent_content(read_file(path), "        "))
        lines.append("    }")
        lines.append("")

    mod_rs_raw = read_file(os.path.join(search_dir, "mod.rs"))
    mod_rs = "\n".join(
        line for line in mod_rs_raw.splitlines()
        if line.strip() not in SEARCH_MOD_LINES_TO_DROP
    ).rstrip()
    if mod_rs:
        lines.append(indent_content(mod_rs))
    lines.append("}")
    lines.append("")

# src/main.rs
main_path = os.path.join(SRC_DIR, "main.rs")
if os.path.exists(main_path):
    main_content = read_file(main_path)
    main_content = main_content.replace("use mushroom_bot::", "use crate::")
    main_content = main_content.replace("mushroom_bot::", "crate::")
    lines.append("// --- src/main.rs ---")
    lines.append(main_content)
    lines.append("")

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Successfully generated {OUTPUT_FILE}")
